# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  auto_review:
    enabled: true                 # auto-review always on
    auto_incremental_review: true # incremental mode for efficiency
    base_branches:
      - ".*"                      # all branches
    allow_manual_override: true   # lets @coderabbitai review force full review
  review_status: true             # shows status messages on PRs
